### ISSUE TITLE
Programming Exam Prep

### ISSUE THREAD

**Issue by sethnielson** [CrimsonVista/NetworkSecurityFall2018#2]
We will be having a programming exam on Wednesday September 5th in class. Please follow these instructions and let me know if you have questions.

1. You must bring a laptop.
2. You must have already installed on your exam laptop:
  (a) A Posix or Posix like environment (Windows users should use Cygwin or WSL)
  (b) Python2 or Python3
  (c) git
3. You must also have a working network connection to reach the class github
4. You may look up information on the Internet, but you must not "talk" (or email or chat) with anyone during the exam.

Between now and the exam, I highly recommend that you learn to write some client/server style networking programs.

**Comment by Mario1412** [comment]
Hi, I got a question for this. Posix is a standard. And what is the "A Posix or Posix-like environment"? Is that mean a IDE or environment like JDK or JRE that we can run the JAVA application? Besides, the mac OSX is a unix-based system, so don't we need to care about POSIX?

**Comment by sethnielson** [comment]
@Mario1412  see https://en.wikipedia.org/wiki/POSIX

If you have a Mac or Linux laptop, you're fine. If you've got Windows, you'll need either Cygwin or WSL

**Comment by sarta8** [comment]
Sir,  do you see any issues or complications with taking the test using a Kali VM?  Thanks.

**Comment by sethnielson** [comment]
@sarta8 None whatsoever, provided you aren't planning to use the Kali VM maliciously ;)
